### ISSUE TITLE
Does Not Work When Windows FIPS Mode is Enabled

### ISSUE THREAD

**Issue by aces-jake** [microsoft/Microsoft-Win32-Content-Prep-Tool#44] opened 2020-05-19 16:06 UTC
When Windows 10 FIPS mode is enabled, the tool errors out:

> File '...intunewin' has faield to be generated
> 
> [===============================                  ]   61%                                                               Done!!!
> 
> System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
>    at System.Security.Cryptography.SHA256Managed..ctor()
>    at Microsoft.Management.Service.IntuneWinAppUtil.EncryptUtil.EncryptFile(String file, AppContext context)
>    at Microsoft.Management.Service.IntuneWinAppUtil.PackageUtil.CreatePackage(String folder, String setupFile, String outputFolder, String catalogFolder)
>    at Microsoft.Management.Service.IntuneWinAppUtil.Program.Main(String[] args)

Here is the registry key for FIPS mode:

`Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy\Enabled
`

The workaround is to temporarily disable FIPS mode, then re-enable it.

**Comment by nikyusof** [comment] 2020-12-04 00:01
Duplicate of #33

**Comment by nikyusof** [comment] 2020-12-04 05:06
Closing this one as it is a duplicate.

**Closed by nikyusof** 2020-12-04 05:06 UTC
