### ISSUE TITLE
Spelling Correction: "Souce"

### ISSUE THREAD

**Issue by ChrisKibble** [microsoft/Microsoft-Win32-Content-Prep-Tool#32] opened 2020-03-31 19:24 UTC
When compressing, the message says:

```
Compressing the souce folder '\\server\share\folder' to 'C:\Users\<User>\AppData\Local\Temp\<guid>\IntuneWinPackage\Contents\IntunePackage.intunewin'
```

With a misspelling of "souce" instead of "source".

**Comment by nikyusof** [comment] 2020-04-22 22:19
Duplicate of #31

**Closed** 2020-04-23 18:53 UTC
