### ISSUE TITLE
Issue with prep tool

### ISSUE THREAD

**Issue by nonfatyogurt19** [microsoft/Microsoft-Win32-Content-Prep-Tool#104] opened 2023-07-18 19:15 UTC
I'm trying to build a win 32 app with the prep tool and every time I start the prep tool, it fails after hitting 70%. The error I'm getting is:

**ERROR System.IO.IOException: The requested operation cannot be performed on a file with a user-mapped section open.**

This happens when I use an EXE, PS script, and and MSI file as the setup file. This issue is happening on multiple workstations with varying settings as well

**Comment by ashek-simeon** [comment] 2023-07-18 21:25
Hi @nonfatyogurt19  ! Alex from Simeon Cloud, here. In case you're open to an alternative, our team has created an open source tool [http://github.com/simeoncloud/IntuneAppBuilder/](https://github.com/simeoncloud/IntuneAppBuilder/) which has the same functionality as this tool (plus the ability to publish apps). We may be avoiding this issue by using a FileStream rather than a MemoryStream. If you give it a shot -- please let us know!

**Comment by ameltzer-MSFT** [comment] 2024-10-17 20:20
This is a likely duplicate of #133

**Closed by ameltzer-MSFT** 2024-10-17 20:20 UTC
Labels: bug, duplicate, triaged
