### ISSUE TITLE
v1.8.5 crashing, v1.8.4 working

### ISSUE THREAD

**Issue by jitauto** [microsoft/Microsoft-Win32-Content-Prep-Tool#114] opened 2023-11-10 13:54 UTC
Let me know if there are crash logs that could be helpful.  I realize I'm not giving much, but it just closes with no error.

**Comment by Sudburr** [comment] 2023-11-10 15:14
Running 1.8.5 in a Windows Console Host (CMD or POWERSHELL 5.x) works.
In Terminal via Powershell 7.3.9 ... won't run at all
In Terminal via Powershell 5.x or CMD sometimes works, sometimes causes terminal window to close
![image](https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/assets/149632684/038954e7-78d6-4a3d-b58b-bce701b669e6)

**Comment by UniverseCitiz3n** [comment] 2023-11-14 14:33
Yeah, I've got the same behaviour...in Terminal it crashes without any errors (both 1.8.5 and 1.8.4).
In plain PowerShell or CMD works fine.

**Comment by thomasjsweet** [comment] 2023-11-15 13:42
1.8.4 and 1.8.5 both crash.  I have spend 20 min trying wrap Chrome.  PowerShell admin worked the last time though I keep trying cmd, terminal, PS 5.1, etc.  Today was the longest I spent trying to get a file. I do it the same exact way each time, and sometimes it works.

I can't post a log because I lose the window closes. Event viewer shows logs below, maybe these will help the team working on this.

Application: IntuneWinAppUtil.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.Console.GetBufferInfo(Boolean, Boolean ByRef)
   at System.Console.get_ForegroundColor()
   at Microsoft.Management.Service.IntuneWinAppUtil.LogUtil.WriteWithForegroundColor(System.ConsoleColor, System.Action)
   at Microsoft.Management.Service.IntuneWinAppUtil.Program.Main(System.String[])



Faulting module name: Microsoft.PowerShell.ConsoleHost.dll, version: 7.3.9.500, time stamp: 0xa2cc9934
Exception code: 0x80131623
Fault offset: 0x000000000004de7b
Faulting process id: 0x0x9178

Faulting application start time: 0x0x1DA17C6AD1E5E72
Faulting application path: C:\Program Files\PowerShell\7\pwsh.exe
Faulting module path: C:\Program Files\PowerShell\7\Microsoft.PowerShell.ConsoleHost.dll
Report Id: 891dbc00-f3d9-48e8-bb3d-bbc8be300fca
Faulting package full name: 
Faulting package-relative application ID: 

and

Faulting module name: Microsoft.PowerShell.ConsoleHost.dll, version: 7.3.9.500, time stamp: 0xa2cc9934
Exception code: 0x80131623
Fault offset: 0x000000000004de7b
Faulting process id: 0x0x9178
Faulting application start time: 0x0x1DA17C6AD1E5E72
Faulting application path: C:\Program Files\PowerShell\7\pwsh.exe
Faulting module path: C:\Program Files\PowerShell\7\Microsoft.PowerShell.ConsoleHost.dll
Report Id: 891dbc00-f3d9-48e8-bb3d-bbc8be300fca
Faulting package full name: 
Faulting package-relative application ID: 

and
Faulting application name: IntuneWinAppUtil.exe, version: 6.2312.30.0, time stamp: 0xb443b0f2
Faulting module name: KERNELBASE.dll, version: 10.0.22621.2428, time stamp: 0x9223bda8
Exception code: 0xe0434352
Fault offset: 0x0000000000064ffc
Faulting process id: 0x0x44E0
Faulting application start time: 0x0x1DA17C7006CEBED
Faulting application path: C:\working\Microsoft-Win32-Content-Prep-Tool-master\IntuneWinAppUtil.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 113b9b33-28e4-4854-9e65-908d072feb6c
Faulting package full name: 
Faulting package-relative application ID: 

and

Faulting application name: OpenConsole.exe, version: 1.18.2310.9002, time stamp: 0x65248ade
Faulting module name: OpenConsole.exe, version: 1.18.2310.9002, time stamp: 0x65248ade
Exception code: 0xc0000094
Fault offset: 0x0000000000002be2
Faulting process id: 0x0x8A64
Faulting application start time: 0x0x1DA17C6AD1DAD54
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.18.2822.0_x64__8wekyb3d8bbwe\OpenConsole.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.18.2822.0_x64__8wekyb3d8bbwe\OpenConsole.exe
Report Id: 1d524ede-56df-46dc-93f7-e973546c5a8f
Faulting package full name: Microsoft.WindowsTerminal_1.18.2822.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

**Comment by markdall** [comment] 2023-11-17 00:00
It crashes for me even under PowerShell, though in my case it did seem to create the .intunewin file first before crashing.

**Comment by thenamelessthing** [comment] 2023-11-17 14:14
I was about to come and check for a more recent version than 1.8.4 because it crashes 2 out of 3 times. But seeing this post, I understand that it's still not fixed...

**Comment by Smith-Rick** [comment] 2023-11-17 18:12
Same Issue

**Comment by markdall** [comment] 2023-11-17 18:57
If you go back a few versions (more than one, less than 5) you get back to a version that functions properly.

**Comment by AxelGauliard** [comment] 2023-11-22 17:56
+1 same to me on a Win 11 23H2 system.
@Sudburr approving your tests with the old and new terminal.

**Comment by diecknet** [comment] 2024-01-12 10:30
Tip: If you don't want to change your default Terminal Engine to Windows Console Host, you can manually run `conhost.exe` and run `IntuneWinAppUtil.exe` there.

**Comment by PaulRosenfeld** [comment] 2024-01-31 19:38
Any word on a fix for this? My PS script is broken. 

For others, you can manually run the tool successfully in CMD by specifying the full path for every parameter. 


```
INFO   Validating parameters
INFO   Validated parameters within 1 milliseconds
INFO   Removing temporary files
ERROR  System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.Management.Service.IntuneWinAppUtil.LogUtil.PrintProgress(AppContext context)
   at Microsoft.Management.Service.IntuneWinAppUtil.PackageUtil.CreatePackage(String folder, String setupFile, String outputFolder, Strin
g catalogFolder)
   at Microsoft.Management.Service.IntuneWinAppUtil.Program.Main(String[] args)

```

**Comment by stevenmiller** [comment] 2024-02-08 14:08
Running from conhost.exe worked for me as a workaround on Windows 11, crashing on 1.8.5 from Windows Terminal.

`Faulting application name: IntuneWinAppUtil.exe, version: 6.2312.30.0, time stamp: 0xb443b0f2
Faulting module name: KERNELBASE.dll, version: 10.0.22621.2792, time stamp: 0x3091b6fb
Exception code: 0xe0434352
Fault offset: 0x000000000006567c
Faulting process id: 0x0x577C
Faulting application start time: 0x0x1DA5A976CA81EAD
Faulting application path: C:\TEMP\IntuneWinAppUtil.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 55e496c6-2862-4a20-b7b1-340ae31dbfd5
Faulting package full name: 
Faulting package-relative application ID: `

`Application: IntuneWinAppUtil.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.Console.GetBufferInfo(Boolean, Boolean ByRef)
   at System.Console.get_ForegroundColor()
   at Microsoft.Management.Service.IntuneWinAppUtil.LogUtil.WriteWithForegroundColor(System.ConsoleColor, System.Action)
   at Microsoft.Management.Service.IntuneWinAppUtil.Program.Main(System.String[])`

**Comment by markdall** [comment] 2024-02-08 16:05
Given that what ought to be a sev 1 pri 0 crashing bug has been sitting here since last November, I'm going to go ahead and assume that this project is dead. I hope the people who made it weren't laid off.

**Comment by ameltzer-MSFT** [comment] 2024-06-10 20:44
Duplicate of #122

**Closed by ameltzer-MSFT** 2024-06-10 20:44 UTC
