### ISSUE TITLE
Crash If Output is Being Redirected

### ISSUE THREAD

**Issue by felixstorm** [microsoft/Microsoft-Win32-Content-Prep-Tool#5] opened 2019-05-07 13:08 UTC
The tool crashes if the output is being redirected. Output of `IntuneWinAppUtil -c SomeSample -s Setup.exe -o . -q > test.log`:
```
Unhandled Exception: System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.set_CursorVisible(Boolean value)
   at Microsoft.Management.Service.IntuneWinAppUtil.Program.Main(String[] args)
```

This is problematic if the tool is being included in automatic (CI) systems when there is no way for the output to be captured (especially in conjunction with https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/issues/4)

**Comment by iainbrighton** [comment] 2019-05-23 15:00
I have big problems running this from PowerShell too. It looks like writing the progress bar causes more problems than solves 😢. Can the progress bar be disabled when running non-interactively, i.e. when using the `-q` switch?

**Comment by jopels** [comment] 2019-06-03 11:50
As a workaround you can call the tool like this:
``Start-Process -FilePath .\IntuneWinAppUtil.exe -ArgumentList "-c `".\$setupFolder`" -s `".\$setupFolder\$setupFile`" -o `".\$outputFolder`""``

**Comment by wiseleaf23** [comment] 2019-07-08 14:17
I too am having the same issues. This is integrated in a script but returns this error. Just launching it in its own windows without parameters works fine, but that is not the reason that I am scripting :)

**Comment by ctolkien** [comment] 2019-07-18 22:11
Running this in Azure DevOps, we're hitting a similar/the same issue:

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.Management.Service.IntuneWinAppUtil.LogUtil' threw an exception. ---> System.IO.IOException: The handle is invalid. |  
-- | --
  |   |  
  | at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) |  
  | at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded) |  
  | at System.Console.get_BufferWidth() |  
  | at Microsoft.Management.Service.IntuneWinAppUtil.LogUtil..cctor() |  
  | --- End of inner exception stack trace --- |  
  | at Microsoft.Management.Service.IntuneWinAppUtil.LogUtil.WriteLineForError(Object error) |  
  | at Microsoft.Management.Service.IntuneWinAppUtil.Program.Main(String[] args)
```

**Comment by wiseleaf23** [comment] 2019-07-19 11:45
I use this workaround by running it in its own PowerShell console :
```
$Command = "$WorkingDir\$IntuneWinAppUtil -c `"$SourceFolder`" -s `"$SourceFileName`" -o $WorkingDir -q"
$Bytes = [System.Text.Encoding]::Unicode.GetBytes($Command)
$EncodedCommand =[Convert]::ToBase64String($Bytes)
Start-Process PowerShell.exe -ArgumentList "-EncodedCommand $EncodedCommand" -Wait
```

**Comment by wiseleaf23** [comment] 2020-04-24 06:15
Might be fixed with the latest release?
> Fixed the ArgumentOutOfRangeException error when running the tool in Windows Terminal.

Issue: https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/issues/29

**Comment by felixstorm** [comment] 2020-04-27 19:20
@wiseleaf23 No, unfortunately the error is still the same, even with the latest release (1.8). A problem has been fixed for Windows Terminal, but output redirection does still not seem to work.

**Comment by mintsoft** [comment] 2020-05-11 13:47
This seems to be a problem in general if you run this through powershell. For example we have Execute.ps1 that does:
```
& "$PSScriptRoot\..\..\tools\Microsoft-Win32-Content-Prep-Tool-1.8.1\IntuneWinAppUtil.exe" -c "$tmp\in" -s "installer.msi" -o "$tmp\out" -q
```

And it blows up with: 
```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.Management.Service.IntuneWinAppUtil.LogUtil' threw an exception. ---> System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetBufferSize(Int32 width, Int32 height)
   at System.Console.set_BufferHeight(Int32 value)
   at Microsoft.Management.Service.IntuneWinAppUtil.LogUtil..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Management.Service.IntuneWinAppUtil.LogUtil.WriteLineForError(Object error)
   at Microsoft.Management.Service.IntuneWinAppUtil.Program.Main(String[] args)
```

Even under 1.8.1

:(

**Comment by malcolmardalon** [comment] 2020-08-16 18:45
Is there any chance this will be fixed soon?  I really need to be able to call the apputil from powershell scripts (e.g. Invoke-Executable -FilePath $IntuneWinAppUtilPath -Arguments "-c ""$($SourceFolder)"" -s ""$($SetupFile)"" -o ""$($OutPutFolder)""" # ... could we have some acknowledgement that this is an issue?

**Comment by jonatanhost** [comment] 2020-10-28 14:14
Are there any workaround for this? I have tried the ones listed above but does not work in an Azure Function environment.

**Comment by mintsoft** [comment] 2020-10-30 08:07
@jonatanhost we run it in cmd and the problem isn't there

**Comment by coaqii** [comment] 2020-11-24 13:45
Does anyone have a workaround for this? 

I have also tried the ones listed above but it does not work in an Azure Function environment

**Comment by onerstam** [comment] 2020-11-25 17:29
Cross reference: https://developercommunity.visualstudio.com/content/problem/1269111/failure-to-run-intunewinapputilexe-on-hosted-devop.html

**Closed** 2020-12-04 05:50 UTC
